#!/usr/bin/env bash
# Profile THIS host's multi-GPU interconnect and write .host_profile, which the training and
# serving scripts source. Run once per machine, before anything else.
#
# Why this exists: the machine we developed on has GPU P2P advertised but non-functional — CUDA
# reports peer access for every pair, yet any NCCL collective using it hangs forever. The
# workaround (NCCL_P2P_DISABLE=1) is REQUIRED there and HARMFUL anywhere else: on a healthy host
# with NVLink it disables NVLink and routes every collective through host memory.
#
# So nothing hardcodes the workaround. This script measures, and writes what your host needs.
#
#   bash scripts/check_host.sh
set -uo pipefail
cd "$(dirname "$0")/.."
REPO="$PWD"
export PATH="$REPO/.venv-train/bin:$PATH"
PROFILE="$REPO/.host_profile"

N=$(nvidia-smi --query-gpu=index --format=csv,noheader | wc -l)
echo "GPUs detected: $N"
echo
echo "=== topology ==="
nvidia-smi topo -m 2>/dev/null | head -n $((N+2))
echo

probe() {  # $1 = n_gpus, $2 = extra env
  local n=$1 env="$2"
  env $env timeout 180 torchrun --nproc_per_node="$n" --master_port=$((29700+n)) \
      scripts/diag_nccl.py 2>&1 | grep -oE "bus bw ~[0-9.]+ GB/s|Watchdog caught" | head -1
}

echo "=== NCCL probe: default settings (P2P enabled) ==="
DEFAULT_RESULT=$(probe "$N" "")
echo "  ${DEFAULT_RESULT:-NO OUTPUT / HUNG}"

P2P_BROKEN=0
if [[ -z "$DEFAULT_RESULT" || "$DEFAULT_RESULT" == *"Watchdog"* ]]; then
  echo
  echo "  !! collectives FAILED or hung with P2P enabled — retrying with NCCL_P2P_DISABLE=1"
  FALLBACK=$(probe "$N" "NCCL_P2P_DISABLE=1")
  echo "  with P2P disabled: ${FALLBACK:-STILL FAILING}"
  [[ -n "$FALLBACK" && "$FALLBACK" != *"Watchdog"* ]] && P2P_BROKEN=1
fi

# Only worth comparing GPU-count scaling when everything must go through host memory.
SUGGESTED_GPUS=$(seq -s, 0 $((N-1)))
if [[ $P2P_BROKEN -eq 1 && $N -ge 8 ]]; then
  echo
  echo "=== P2P is broken here; checking whether fewer GPUs are faster ==="
  HALF=$((N/2))
  R_HALF=$(CUDA_VISIBLE_DEVICES=$(seq -s, 0 $((HALF-1))) probe "$HALF" "NCCL_P2P_DISABLE=1")
  echo "  ${HALF} GPUs: ${R_HALF:-n/a}"
  echo "  ${N} GPUs: (measured above)"
  echo "  If the half-node number is much higher, prefer it and raise gradient_accumulation_steps"
  echo "  to keep the global batch size constant."
fi

{
  echo "# Generated by scripts/check_host.sh on $(date -u +%Y-%m-%dT%H:%MZ) — host $(hostname)"
  echo "# Sourced by scripts/20_train.sh and scripts/40_serve_teacher.sh."
  if [[ $P2P_BROKEN -eq 1 ]]; then
    echo "# This host advertises GPU P2P but collectives using it hang. Workaround required."
    echo "export NCCL_P2P_DISABLE=1"
  else
    echo "# GPU P2P works here. Do NOT set NCCL_P2P_DISABLE — it would disable NVLink/P2P"
    echo "# and force collectives through host memory."
    echo "# (no NCCL overrides needed)"
  fi
  echo "export PYTORCH_CUDA_ALLOC_CONF=\${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"
} > "$PROFILE"

echo
echo "wrote $PROFILE:"
sed 's/^/  /' "$PROFILE"
[[ $P2P_BROKEN -eq 1 ]] && echo "
NOTE: P2P is broken on this host. That is a machine configuration problem (likely ACS or IOMMU
on the PCIe bridges) and needs root to fix properly. Until then collectives run through host
shared memory, which is several times slower."
exit 0
